### ISSUE TITLE
systemd startup issue

### ISSUE THREAD

**Issue by usergoodvery** [mrlesmithjr/ansible-gerrit#3]
hi
the role fails to start the service via systemd: the gerrit user can't write to the pid file when the process is run under gerrit user. Should the /var/gerrit be owned by gerrit user, instead of root?

May 20 00:51:51 db.ufsrv systemd[1]: Starting Web based code review and project management for Git based projects...
May 20 00:51:51 db.ufsrv gerrit[22223]: Starting Gerrit Code Review: start-stop-daemon: unable to open pidfile '/var/gerrit/logs/gerrit.pid' for writing (Permission denied)
May 20 00:51:51 db.ufsrv gerrit[22223]: start-stop-daemon: child returned error exit status 2 (No such file or directory)
May 20 00:51:51 db.ufsrv systemd[1]: gerrit.service: Control process exited, code=exited status=2
May 20 00:51:51 db.ufsrv systemd[1]: Failed to start Web based code review and project management for Git based projects.
May 20 00:51:51 db.ufsrv systemd[1]: gerrit.service: Unit entered failed state.
May 20 00:51:51 db.ufsrv systemd[1]: gerrit.service: Failed with result 'exit-code'.

The installation seems to be OK:
 /var/gerrit/bin/gerrit.sh status
Checking arguments to Gerrit Code Review:
  GERRIT_SITE            =  /var/gerrit
  GERRIT_CONFIG          =  /var/gerrit/etc/gerrit.config
  GERRIT_PID             =  /var/gerrit/logs/gerrit.pid
  GERRIT_TMP             =  /var/gerrit/tmp
  GERRIT_WAR             =  /opt/gerrit/gerrit.war
  GERRIT_FDS             =  1024
  GERRIT_USER            =  gerrit
  GERRIT_STARTUP_TIMEOUT =  90
  JAVA                   =  /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  JAVA_OPTIONS           =
  RUN_EXEC               =  /usr/bin/perl -e '$x=$ENV{JAVA};exec $x @ARGV;die $!' -- GerritCodeReview
  RUN_ARGS               =  -jar /opt/gerrit/gerrit.war daemon -d /var/gerrit

**Comment by mrlesmithjr** [comment]
@usergoodvery I'll take a look into this soon.

**Comment by mrlesmithjr** [comment]
@usergoodvery This should be resolved now.

**Comment by usergoodvery** [comment]
thank you
